### ISSUE TITLE
Feature Wish: work without relay

### ISSUE THREAD

**Issue by splitbrain** [axllent/sndmail#12]
It would be cool if, instead of simply sending the message to a relay SMTP, sndmail could deliver the mail directly to the recipient(s) MX SMTP. I'm aware that one would lose retry-behavior of a real SMTP server, but the return code could signal any errors and leave the user to retry later.

This should be optional of course.

**Comment by axllent** [comment]
Hi @splitbrain. Whilst I agree that it would be cool, it is completely out of scope for any sendmail implementation to support this. Email delivery is far more complicated than it sounds including:
- Not all domains have MX records, and MX records usually point to other hostnames which in turn need t be understood / resolved
- Temporary deferral (graylisting) of messages is now common practice, especially for low-volume SMTP servers, so retrying is a requirement
- Handling / understanding temporary errors
- A software-understanding of different security protocols and how to negotiate those to deliver mail
....

To build in support for what you want would effectively require a sndmail to be a full "Postfx clone", which is why sendmail (and all the sendmail clones like sndmail) do not even attempt this. It's like wanting Notepad to support different fonts, embedding of images and tables - you would just use Word / LibreOffice etc instead.

So sorry, as nice as it sounds, it's not practical at all. If you're simply requiring a SMTP relay, then you can set up sndmail with something like Mailgun and let them do the delivery.

**Comment by splitbrain** [comment]
Ah, I guess I should have explained better. I am well aware of the intricacies of modern mail handling and I am absolutely not asking to handle them.

My idea was more of a very simple attempt to deliver the mail (as you would have done maybe 30 years ago) and immediately fail if that doesn't succeed. Basically any code that's not an Accept would mean a fail and be reflected in the tool's return code. 

That is probably what you are doing for talking to the relay host right now as well. If the relay tells you to try again later you will not wait an hour but signal a fail to the caller, right?

Why do I think this would be useful?

I was thinking about using sndmail as the delivery agent for an application in a Docker container. When this container is run in a company LAN, it is likely that mails will only ever be sent to colleagues and that the MX is local. That local MX will accept mails from the LAN for local delivery.

In this particular case, the container's mail delivery would just magically work. Someone starting it would not need to know anything about setting up mail connection parameters.

Everyone else would of course configure a smart host.

Anyway, I understand if this is out of scope for your project.

**Comment by axllent** [comment]
Thanks for the explanation. Years of development has taught me a few things, one of which is think twice before adding a feature that does not comply with current standards. Doing so will likely result in bug reports because "it's not working" - at which point I have three choices:
1. Remove the feature because it's not compliant - I obviously can't do that once I've added it
2. Do nothing, in which case the reporter is correct but I just won't fix it, so sndmail becomes a buggy implementation - I really don't like that
3. Fix the feature to be compliant - in which case I end up adding (and maintaining) a whole bunch of functionality which was never intended for this software in the first place

I will politely decline to add this feature, and I hope you understand my reasoning for doing so. I'm sure there must already be other small mail servers out there that already handle your requirement.
